### ISSUE TITLE
Need an official release

### ISSUE THREAD

**Issue by leofang** [conda-forge/libcugraph-feedstock#6]
Currently these two lines 
https://github.com/conda-forge/libcugraph-feedstock/blob/ae9ef496797bee583b807d56cf52ba2dfbf0c3fd/recipe/conda_build_config.yaml#L45-L46
make the package published under the `libcugraph_dev` label. This is for development/release candidates. However, I think v0.19.0 is just released, and we should have a separate branch for the official releases, otherwise we cannot do
```
conda install -c conda-forge libcugraph
```

@rlratzel Could you do two things for me please?
1. Rename the current master to, say, `rc` so that it continues to publish packages under `libcugraph_dev `
2. Create a new branch (master) *without* the `libcugraph_dev` label that publishes v0.19.0 and the future releases 

This is blocking CuPy v9.0.0 (https://github.com/conda-forge/cupy-feedstock/pull/123).

**Comment by leofang** [comment]
> @rlratzel Could you do two things for me please?
> 
> 1. Rename the current master to, say, `rc` so that it continues to publish packages under `libcugraph_dev `
> 2. Create a new branch (master) _without_ the `libcugraph_dev` label that publishes v0.19.0 and the future releases

I sent a PR for No. 2, but @rlratzel I still need you to do the first bit as I am not a maintainer 🙂

**Comment by kkraus14** [comment]
I don't think there's an intention to continue publishing pre-release builds here, so can we just migrate the current main branch to the 0.19.0 release and carry on with only release versions?

**Comment by leofang** [comment]
OK @kkraus14, then that's exactly what #7 will do!
